model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
general_settings:
  master_key: sk-mysecretkey1234
  allowed_origins: ["https://gritbot.netlify.app"]