[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/pdfs/*"
  to = "/pdfs/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200